name: gisandbox
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - rise
  - gdal
  - fiona  
  - rasterio
  - pillow
  - ipyleaflet
  - osmnx
  - mapclassify
  - mplleaflet
  - pip:
          # - numpy
          # - scipy
          # - pandas
          # - keplergl
    - geopandas
    - shapely
    - folium
    - matplotlib
    - tensorflow
    - mordecai
